### ISSUE TITLE
Is there an API documentation for the example?

### ISSUE THREAD

**Issue by jayavanth** [Firstyear/webauthn-rs#13]
What's the sequence of API calls to register a user and the 2FA device and then logging in and using the 2FA device for auth?

**Comment by Firstyear** [comment]
Hi there,

There is quite a bit of documentation at: https://docs.rs/webauthn-rs/0.1.3/webauthn_rs/

https://docs.rs/webauthn-rs/0.1.3/webauthn_rs/trait.WebauthnConfig.html  describes how you configure and provide persistence to the Webauthn application. 

https://docs.rs/webauthn-rs/0.1.3/webauthn_rs/struct.Webauthn.html  describes the order of operations and how they are called from your application, IE how you would connect routes.

Is there a change to the docs that would have made it clearer to find these two resources?

Does reading the source code in here help?: https://github.com/Firstyear/webauthn-rs/tree/master/examples/actix

Note that the templates and js in the project are both used by that example by the way.

**Comment by jayavanth** [comment]
@Firstyear Yes, I think add a link to https://docs.rs/webauthn-rs/0.1.3/webauthn_rs/ to README. I would not have found it if you had not mentioned it here.

I'm new to Rust so maybe that's why things look alien to me.

I built the example with
`cargo build --example actix  `
and I'm running
`./target/debug/examples/actix` which starts a http server at `http://localhost:8080/auth/`

What URL should I go to in my browser to go to the login page (template/js) ?

**Comment by Firstyear** [comment]
Hey there,

I would be happy to answer these questions but I’m traveling today, so can I respond in 1 day time? Thanks for asking these things, it will help me improve the project :)

William

**Comment by jayavanth** [comment]
Used `127.0.0.1` instead of localhost and it worked. Just to confirm, this library doesn't support FIDO keys yet, right?

**Comment by Firstyear** [comment]
The library only supports fido u2f keys today.

If localhost didnt work you have a problem in you etc/hosts file most likely. 

Sorry for short response.

William

**Comment by Firstyear** [comment]
Hey there

So longer answer: You wont have a working setup if you use http://127.0.0.1:8080/auth. This is because the origin is based on the ip/address, and the example is configured with an origin of localhost. That would cause all registrations and authentications to fail.

You need to look into why your system fails to resolve "localhost" to 127.0.0.1.

I'm currently updating the documentation to include better links, a README.md in the examples, with how to run and use, as well as some todo.

Hope this helps,
