### ISSUE TITLE
support "packed" attestation

### ISSUE THREAD

**Issue by robjtede** [Firstyear/webauthn-rs#17]
Found this while attempting to register with TouchID.

[Info on the checks required to support this.](https://medium.com/@herrjemand/verifying-fido2-packed-attestation-a067a9b2facd)

_There may be time in my near future to PR this._

**Comment by Firstyear** [comment]
Hey there! I'd be happy to review and include this format for attestation. A really great implementation is https://github.com/duo-labs/webauthn and they have test vectors as well. 

It's best if we can generate our own of course, and that's generally what I would use to drive the development. It's also a great idea to follow the w3c specification very closely (you'll probably note all the comments in my implementation of fido u2f :) )

Thanks!
