### ISSUE TITLE
Support user verification required

### ISSUE THREAD

**Issue by Firstyear** [Firstyear/webauthn-rs#7]
I have not been able to work out how to trigger "user verification" = true on challenges. We should determine how to request these values, and check these are respected properly.

**Comment by aseigler** [comment]
Consider the case where the relying party only wants authenticators that support UV, but also the case that the server doesn't care, but a particular user really wants to make sure that when THEY authenticate, the server will require UV.

**Comment by Firstyear** [comment]
I wrote this to support "per-user" UV policies, which is implemented by the callback system so that a site-policy can be developed to determine who requires UV. 

I'm not 100% sure about the discouraged policy, at the moment I fail the operation if policy is discouraged but UV is true, which imo seems like a possible issue or invalid handling. I can also see it would be valid for discouraged to ignore the UV flag (just like preferred), meaning that only Required enforces any state over the UV bit.

So I'll close this as "done" because the code is implemented, but I'd appreciate your comments on the above :)
